sudo: required

services:
  - docker

before_install:
  - docker build -t docker-react -f Dockerfile.dev .

# note that npm run test should exit after the first run
# script:
#  - docker run docker-react npm run test -- --coverage

script:
 - docker run -e CI=true docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "docker-react"
  env: "Docker-react-env"
  bucket_name: "elasticbeanstalk-eu-central-1-156173772875"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $aws-access-key
  secret-acces-key: "$aws-secret-key"
